/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DeliveryPartnersRouteImport } from './routes/delivery-partners'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarkingIndexRouteImport } from './routes/marking.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MarkingWardRouteImport } from './routes/marking.ward'
import { Route as MarkingPanchayathRouteImport } from './routes/marking.panchayath'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryPartnersRoute = DeliveryPartnersRouteImport.update({
  id: '/delivery-partners',
  path: '/delivery-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkingIndexRoute = MarkingIndexRouteImport.update({
  id: '/marking/',
  path: '/marking/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MarkingWardRoute = MarkingWardRouteImport.update({
  id: '/marking/ward',
  path: '/marking/ward',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkingPanchayathRoute = MarkingPanchayathRouteImport.update({
  id: '/marking/panchayath',
  path: '/marking/panchayath',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/delivery-partners': typeof DeliveryPartnersRoute
  '/landing': typeof LandingRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/marking/panchayath': typeof MarkingPanchayathRoute
  '/marking/ward': typeof MarkingWardRoute
  '/admin/': typeof AdminIndexRoute
  '/marking/': typeof MarkingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delivery-partners': typeof DeliveryPartnersRoute
  '/landing': typeof LandingRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/marking/panchayath': typeof MarkingPanchayathRoute
  '/marking/ward': typeof MarkingWardRoute
  '/admin': typeof AdminIndexRoute
  '/marking': typeof MarkingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/delivery-partners': typeof DeliveryPartnersRoute
  '/landing': typeof LandingRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/marking/panchayath': typeof MarkingPanchayathRoute
  '/marking/ward': typeof MarkingWardRoute
  '/admin/': typeof AdminIndexRoute
  '/marking/': typeof MarkingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/delivery-partners'
    | '/landing'
    | '/admin/locations'
    | '/admin/staff'
    | '/admin/users'
    | '/marking/panchayath'
    | '/marking/ward'
    | '/admin/'
    | '/marking/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/delivery-partners'
    | '/landing'
    | '/admin/locations'
    | '/admin/staff'
    | '/admin/users'
    | '/marking/panchayath'
    | '/marking/ward'
    | '/admin'
    | '/marking'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/delivery-partners'
    | '/landing'
    | '/admin/locations'
    | '/admin/staff'
    | '/admin/users'
    | '/marking/panchayath'
    | '/marking/ward'
    | '/admin/'
    | '/marking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeliveryPartnersRoute: typeof DeliveryPartnersRoute
  LandingRoute: typeof LandingRoute
  MarkingPanchayathRoute: typeof MarkingPanchayathRoute
  MarkingWardRoute: typeof MarkingWardRoute
  MarkingIndexRoute: typeof MarkingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-partners': {
      id: '/delivery-partners'
      path: '/delivery-partners'
      fullPath: '/delivery-partners'
      preLoaderRoute: typeof DeliveryPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marking/': {
      id: '/marking/'
      path: '/marking'
      fullPath: '/marking/'
      preLoaderRoute: typeof MarkingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/marking/ward': {
      id: '/marking/ward'
      path: '/marking/ward'
      fullPath: '/marking/ward'
      preLoaderRoute: typeof MarkingWardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marking/panchayath': {
      id: '/marking/panchayath'
      path: '/marking/panchayath'
      fullPath: '/marking/panchayath'
      preLoaderRoute: typeof MarkingPanchayathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLocationsRoute: AdminLocationsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DeliveryPartnersRoute: DeliveryPartnersRoute,
  LandingRoute: LandingRoute,
  MarkingPanchayathRoute: MarkingPanchayathRoute,
  MarkingWardRoute: MarkingWardRoute,
  MarkingIndexRoute: MarkingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
