/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DeliveryPartnersRouteImport } from './routes/delivery-partners'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarkingIndexRouteImport } from './routes/marking.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MarkingWardRouteImport } from './routes/marking.ward'
import { Route as MarkingPanchayathRouteImport } from './routes/marking.panchayath'
import { Route as MapPanchayathRouteImport } from './routes/map.panchayath'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMappingRouteImport } from './routes/admin.mapping'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminMappingIndexRouteImport } from './routes/admin.mapping.index'
import { Route as AdminMappingWardRouteImport } from './routes/admin.mapping.ward'
import { Route as AdminMappingPanchayathRouteImport } from './routes/admin.mapping.panchayath'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryPartnersRoute = DeliveryPartnersRouteImport.update({
  id: '/delivery-partners',
  path: '/delivery-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkingIndexRoute = MarkingIndexRouteImport.update({
  id: '/marking/',
  path: '/marking/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MarkingWardRoute = MarkingWardRouteImport.update({
  id: '/marking/ward',
  path: '/marking/ward',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkingPanchayathRoute = MarkingPanchayathRouteImport.update({
  id: '/marking/panchayath',
  path: '/marking/panchayath',
  getParentRoute: () => rootRouteImport,
} as any)
const MapPanchayathRoute = MapPanchayathRouteImport.update({
  id: '/map/panchayath',
  path: '/map/panchayath',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMappingRoute = AdminMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMappingIndexRoute = AdminMappingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMappingRoute,
} as any)
const AdminMappingWardRoute = AdminMappingWardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => AdminMappingRoute,
} as any)
const AdminMappingPanchayathRoute = AdminMappingPanchayathRouteImport.update({
  id: '/panchayath',
  path: '/panchayath',
  getParentRoute: () => AdminMappingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/delivery-partners': typeof DeliveryPartnersRoute
  '/landing': typeof LandingRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/mapping': typeof AdminMappingRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/map/panchayath': typeof MapPanchayathRoute
  '/marking/panchayath': typeof MarkingPanchayathRoute
  '/marking/ward': typeof MarkingWardRoute
  '/admin/': typeof AdminIndexRoute
  '/marking/': typeof MarkingIndexRoute
  '/admin/mapping/panchayath': typeof AdminMappingPanchayathRoute
  '/admin/mapping/ward': typeof AdminMappingWardRoute
  '/admin/mapping/': typeof AdminMappingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delivery-partners': typeof DeliveryPartnersRoute
  '/landing': typeof LandingRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/map/panchayath': typeof MapPanchayathRoute
  '/marking/panchayath': typeof MarkingPanchayathRoute
  '/marking/ward': typeof MarkingWardRoute
  '/admin': typeof AdminIndexRoute
  '/marking': typeof MarkingIndexRoute
  '/admin/mapping/panchayath': typeof AdminMappingPanchayathRoute
  '/admin/mapping/ward': typeof AdminMappingWardRoute
  '/admin/mapping': typeof AdminMappingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/delivery-partners': typeof DeliveryPartnersRoute
  '/landing': typeof LandingRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/mapping': typeof AdminMappingRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/map/panchayath': typeof MapPanchayathRoute
  '/marking/panchayath': typeof MarkingPanchayathRoute
  '/marking/ward': typeof MarkingWardRoute
  '/admin/': typeof AdminIndexRoute
  '/marking/': typeof MarkingIndexRoute
  '/admin/mapping/panchayath': typeof AdminMappingPanchayathRoute
  '/admin/mapping/ward': typeof AdminMappingWardRoute
  '/admin/mapping/': typeof AdminMappingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/delivery-partners'
    | '/landing'
    | '/admin/locations'
    | '/admin/mapping'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/map/panchayath'
    | '/marking/panchayath'
    | '/marking/ward'
    | '/admin/'
    | '/marking/'
    | '/admin/mapping/panchayath'
    | '/admin/mapping/ward'
    | '/admin/mapping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/delivery-partners'
    | '/landing'
    | '/admin/locations'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/map/panchayath'
    | '/marking/panchayath'
    | '/marking/ward'
    | '/admin'
    | '/marking'
    | '/admin/mapping/panchayath'
    | '/admin/mapping/ward'
    | '/admin/mapping'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/delivery-partners'
    | '/landing'
    | '/admin/locations'
    | '/admin/mapping'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/users'
    | '/map/panchayath'
    | '/marking/panchayath'
    | '/marking/ward'
    | '/admin/'
    | '/marking/'
    | '/admin/mapping/panchayath'
    | '/admin/mapping/ward'
    | '/admin/mapping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeliveryPartnersRoute: typeof DeliveryPartnersRoute
  LandingRoute: typeof LandingRoute
  MapPanchayathRoute: typeof MapPanchayathRoute
  MarkingPanchayathRoute: typeof MarkingPanchayathRoute
  MarkingWardRoute: typeof MarkingWardRoute
  MarkingIndexRoute: typeof MarkingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-partners': {
      id: '/delivery-partners'
      path: '/delivery-partners'
      fullPath: '/delivery-partners'
      preLoaderRoute: typeof DeliveryPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marking/': {
      id: '/marking/'
      path: '/marking'
      fullPath: '/marking/'
      preLoaderRoute: typeof MarkingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/marking/ward': {
      id: '/marking/ward'
      path: '/marking/ward'
      fullPath: '/marking/ward'
      preLoaderRoute: typeof MarkingWardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marking/panchayath': {
      id: '/marking/panchayath'
      path: '/marking/panchayath'
      fullPath: '/marking/panchayath'
      preLoaderRoute: typeof MarkingPanchayathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/panchayath': {
      id: '/map/panchayath'
      path: '/map/panchayath'
      fullPath: '/map/panchayath'
      preLoaderRoute: typeof MapPanchayathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapping': {
      id: '/admin/mapping'
      path: '/mapping'
      fullPath: '/admin/mapping'
      preLoaderRoute: typeof AdminMappingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapping/': {
      id: '/admin/mapping/'
      path: '/'
      fullPath: '/admin/mapping/'
      preLoaderRoute: typeof AdminMappingIndexRouteImport
      parentRoute: typeof AdminMappingRoute
    }
    '/admin/mapping/ward': {
      id: '/admin/mapping/ward'
      path: '/ward'
      fullPath: '/admin/mapping/ward'
      preLoaderRoute: typeof AdminMappingWardRouteImport
      parentRoute: typeof AdminMappingRoute
    }
    '/admin/mapping/panchayath': {
      id: '/admin/mapping/panchayath'
      path: '/panchayath'
      fullPath: '/admin/mapping/panchayath'
      preLoaderRoute: typeof AdminMappingPanchayathRouteImport
      parentRoute: typeof AdminMappingRoute
    }
  }
}

interface AdminMappingRouteChildren {
  AdminMappingPanchayathRoute: typeof AdminMappingPanchayathRoute
  AdminMappingWardRoute: typeof AdminMappingWardRoute
  AdminMappingIndexRoute: typeof AdminMappingIndexRoute
}

const AdminMappingRouteChildren: AdminMappingRouteChildren = {
  AdminMappingPanchayathRoute: AdminMappingPanchayathRoute,
  AdminMappingWardRoute: AdminMappingWardRoute,
  AdminMappingIndexRoute: AdminMappingIndexRoute,
}

const AdminMappingRouteWithChildren = AdminMappingRoute._addFileChildren(
  AdminMappingRouteChildren,
)

interface AdminRouteChildren {
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminMappingRoute: typeof AdminMappingRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLocationsRoute: AdminLocationsRoute,
  AdminMappingRoute: AdminMappingRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DeliveryPartnersRoute: DeliveryPartnersRoute,
  LandingRoute: LandingRoute,
  MapPanchayathRoute: MapPanchayathRoute,
  MarkingPanchayathRoute: MarkingPanchayathRoute,
  MarkingWardRoute: MarkingWardRoute,
  MarkingIndexRoute: MarkingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
